export const seedData = {
  profile: {
    school: "한국대학교",
    status: "재학",
    grade: "3학년",
    major: "컴퓨터공학과",
    residence: "서울특별시 마포구",
    hometown: "충청남도 천안시",
    gpa: "3.8 / 4.5",
    incomeBracket: "3구간",
    residenceMonths: "6개월 이상",
    benefitPreference: "생활비/주거비 우선",
    specialConditions: ["지역인재", "소득연계 관심"],
    contestInterests: ["IT/소프트웨어", "창업/아이디어"],
    skills: ["개발", "기획", "발표"],
    teamPreference: "팀 가능",
    weeklyHours: "주 5~10시간",
    contestGoal: "포트폴리오",
    completion: 78
  },
  savedOpportunityIds: ["opp-001", "opp-003"],
  checkedDocs: {
    "opp-001": ["재학증명서"]
  },
  applications: {
    "opp-001": {
      status: "서류준비",
      reminderEnabled: true,
      updatedAt: null
    },
    "opp-003": {
      status: "검토중",
      reminderEnabled: false,
      updatedAt: null
    }
  },
  sources: [
    {
      id: "src-youthcenter",
      name: "온통청년 청년정책 API",
      type: "API",
      organization: "한국고용정보원",
      url: "https://www.youthcenter.go.kr/opi/youthPlcyList.do",
      status: "NEEDS_KEY",
      priority: 1,
      lastRunAt: null,
      lastResult: "YOUTHCENTER_API_KEY 환경변수 필요",
      coverage: 0,
      notes: "청년정책/청년공간 공식 API. 인증키 발급 후 XML 응답 파싱."
    },
    {
      id: "src-gov24",
      name: "보조금24 공공서비스 정보",
      type: "API",
      organization: "행정안전부",
      url: "https://www.data.go.kr/",
      status: "NEEDS_KEY",
      priority: 2,
      lastRunAt: null,
      lastResult: "PUBLIC_SERVICE_API_KEY 환경변수 필요",
      coverage: 0,
      notes: "중앙부처/지자체/공공기관 수혜서비스 공식 API."
    },
    {
      id: "src-kosaf",
      name: "한국장학재단 푸른등대 장학금",
      type: "HTML",
      organization: "한국장학재단",
      url: "https://www.kosaf.go.kr/ko/scholar.do?pg=scholarship05_11_01&type=tuition",
      status: "ACTIVE",
      priority: 3,
      lastRunAt: null,
      lastResult: "대기 중",
      coverage: 68,
      notes: "공개 장학금 소개 페이지에서 장학금명/조건 후보를 추출."
    },
    {
      id: "src-scholarship-commons",
      name: "한국장학협회 장학 프로그램",
      type: "HTML",
      organization: "한국장학협회",
      url: "https://www.scholarship.or.kr/lab/intelligence?use1=2&use2=5",
      status: "ACTIVE",
      priority: 4,
      lastRunAt: null,
      lastResult: "대기 중",
      coverage: 54,
      notes: "공개 장학 프로그램 목록에서 생활비/지역연고 장학금 후보 추출."
    },
    {
      id: "src-contest-official",
      name: "공식 공모전/아이디어 대회 수동 등록",
      type: "MANUAL",
      organization: "오퍼가디언 운영",
      url: "manual://contest-review",
      status: "PAUSED",
      priority: 5,
      lastRunAt: null,
      lastResult: "공식 공모전 URL을 운영자가 등록하면 AI 검수 큐로 전환",
      coverage: 35,
      notes: "공공기관/대학/기업 공식 공모전 URL을 운영자가 등록하고 AI 검수 큐로 보내는 소스."
    }
  ],
  crawlRuns: [],
  opportunities: [
    {
      id: "opp-001",
      title: "마포구 지역인재 생활비 장학생",
      organization: "마포인재육성장학재단",
      region: "서울 마포구",
      schoolScope: "전국 대학",
      category: "생활비",
      benefitType: "생활비성 장학금",
      amountText: "최대 200만원",
      amountMax: 2000000,
      deadline: "2026-05-11 18:00",
      dday: 4,
      sourceType: "지자체 장학재단",
      documents: ["재학증명서", "성적증명서", "주민등록초본", "추천서"],
      source: "mapo-foundation",
      rules: {
        regionKeywords: ["마포구"],
        schoolAny: true,
        minGpa: 3,
        maxIncomeBracket: null,
        majorKeywords: [],
        requiredUnknowns: ["공고일 기준 6개월 이상 주민등록 유지 여부"],
        warnings: ["학교장 또는 총장 추천서가 필요할 수 있습니다."]
      }
    },
    {
      id: "opp-002",
      title: "충남 미래인재 재능키움 장학사업",
      organization: "충남평생교육인재육성진흥원",
      region: "충청남도",
      schoolScope: "충남 출신 대학생",
      category: "장학금",
      benefitType: "재능개발 장학금",
      amountText: "200만원",
      amountMax: 2000000,
      deadline: "2026-05-15 17:00",
      dday: 8,
      sourceType: "지자체 API + PDF",
      documents: ["신청서", "재학증명서", "활동계획서", "주민등록등본"],
      source: "chungnam-api",
      rules: {
        regionKeywords: ["충청남도", "충남", "천안시"],
        schoolAny: true,
        minGpa: null,
        maxIncomeBracket: null,
        majorKeywords: [],
        requiredUnknowns: ["보호자 주소지 기준을 적용하는지 확인 필요", "활동계획서 제출 여부"],
        warnings: ["선발 후 결과보고회 참여가 필요할 수 있습니다."]
      }
    },
    {
      id: "opp-003",
      title: "푸른등대 초록사다리 대학생 멘토",
      organization: "한국장학재단 / NH농협은행",
      region: "전국",
      schoolScope: "전국 대학",
      category: "교육/연수",
      benefitType: "활동비 + 장학금",
      amountText: "최대 220만원",
      amountMax: 2200000,
      deadline: "2026-05-15 18:00",
      dday: 8,
      sourceType: "공공기관",
      documents: ["온라인 신청서", "자기소개서", "활동 가능 일정"],
      source: "kosaf",
      rules: {
        regionKeywords: ["전국"],
        schoolAny: true,
        minGpa: 2.5,
        maxIncomeBracket: null,
        majorKeywords: [],
        requiredUnknowns: ["멘토링 가능 일정"],
        warnings: ["활동 시간 미충족 시 장학금 지급이 제한될 수 있습니다."]
      }
    },
    {
      id: "opp-004",
      title: "서울 청년 월세 특별지원",
      organization: "서울특별시",
      region: "서울",
      schoolScope: "청년 일반",
      category: "주거비",
      benefitType: "주거비 지원",
      amountText: "월 20만원",
      amountMax: 2400000,
      deadline: "2026-05-30 23:59",
      dday: 23,
      sourceType: "청년정책 API",
      documents: ["임대차계약서", "월세 이체증", "가족관계증명서"],
      source: "youth-policy-api",
      rules: {
        regionKeywords: ["서울"],
        schoolAny: true,
        minGpa: null,
        maxIncomeBracket: 5,
        majorKeywords: [],
        requiredUnknowns: ["임대차계약 여부", "월세 금액", "가구 소득 기준"],
        warnings: ["소득/재산 기준을 충족하지 않으면 제외될 수 있습니다."]
      }
    },
    {
      id: "opp-005",
      title: "한국고등교육재단 인재림 장학생",
      organization: "한국고등교육재단",
      region: "전국",
      schoolScope: "전국 대학",
      category: "장학금",
      benefitType: "학업장려금",
      amountText: "800만원 + 활동비",
      amountMax: 8000000,
      deadline: "2026-05-20 18:00",
      dday: 13,
      sourceType: "민간재단 PDF",
      documents: ["지원서", "성적증명서", "자기소개서", "교수 추천서"],
      source: "private-foundation",
      rules: {
        regionKeywords: ["전국"],
        schoolAny: true,
        minGpa: 3.7,
        maxIncomeBracket: null,
        majorKeywords: [],
        requiredUnknowns: ["면접/에세이 평가 기준", "기존 수혜 이력 제한"],
        warnings: ["경쟁률이 높고 자기소개서 품질이 중요합니다."]
      }
    },
    {
      id: "opp-006",
      title: "보건계열 연구지원 장학생",
      organization: "보건장학회",
      region: "전국",
      schoolScope: "보건계열",
      category: "장학금",
      benefitType: "연구지원금",
      amountText: "500만원",
      amountMax: 5000000,
      deadline: "2026-05-11 16:00",
      dday: 4,
      sourceType: "민간재단",
      documents: ["연구계획서", "성적증명서", "지도교수 추천서"],
      source: "health-foundation",
      rules: {
        regionKeywords: ["전국"],
        schoolAny: true,
        minGpa: 3.2,
        maxIncomeBracket: null,
        majorKeywords: ["보건", "간호", "의학", "약학"],
        requiredUnknowns: [],
        warnings: ["전공 조건이 보건계열로 제한됩니다."]
      }
    },
    {
      id: "opp-101",
      title: "전국 대학생 AI 서비스 아이디어 공모전",
      organization: "한국지능정보사회진흥원",
      region: "전국",
      schoolScope: "대학생 개인/팀",
      category: "공모전",
      benefitType: "아이디어/서비스 기획 공모전",
      amountText: "상금 총 1,000만원",
      amountMax: 10000000,
      prizeText: "대상 500만원, 우수상 200만원, 멘토링 제공",
      deadline: "2026-05-28 18:00",
      dday: 21,
      sourceType: "공식 공모전 수동 등록",
      documents: ["참가신청서", "서비스 기획서", "개인정보 동의서"],
      source: "contest-ai-service",
      contestFields: ["AI/데이터", "IT/소프트웨어", "창업/아이디어"],
      submissionTypes: ["기획서", "프로토타입 선택"],
      teamMode: "개인/팀 모두 가능",
      difficulty: "중간",
      portfolioValue: "높음",
      rules: {
        contestFields: ["AI/데이터", "IT/소프트웨어", "창업/아이디어"],
        skillKeywords: ["기획", "개발", "데이터분석", "발표", "PM"],
        submissionTypes: ["기획서", "프로토타입"],
        teamModes: ["개인 선호", "팀 가능", "팀 선호", "팀원 찾는 중"],
        minWeeklyHours: 5,
        goalKeywords: ["포트폴리오", "창업 검증", "수상 경력"],
        requiredUnknowns: ["세부 심사기준", "저작권 귀속 조건"],
        warnings: ["제출물 저작권과 공개 범위를 공고 원문에서 확인해야 합니다."]
      }
    },
    {
      id: "opp-102",
      title: "로컬 관광 콘텐츠 숏폼 공모전",
      organization: "한국관광공사",
      region: "전국",
      schoolScope: "대학생/청년 개인 또는 팀",
      category: "공모전",
      benefitType: "영상/콘텐츠 공모전",
      amountText: "상금 총 700만원",
      amountMax: 7000000,
      prizeText: "상금, 공식 채널 게재, 지역 팸투어",
      deadline: "2026-05-19 17:00",
      dday: 12,
      sourceType: "공식 공모전 수동 등록",
      documents: ["참가신청서", "30~60초 영상", "작품 설명서"],
      source: "contest-local-shorts",
      contestFields: ["영상/콘텐츠", "지역/관광", "기획/마케팅"],
      submissionTypes: ["영상", "작품 설명서"],
      teamMode: "개인/팀 모두 가능",
      difficulty: "낮음~중간",
      portfolioValue: "중간",
      rules: {
        contestFields: ["영상/콘텐츠", "지역/관광", "기획/마케팅"],
        skillKeywords: ["영상편집", "기획", "마케팅", "글쓰기"],
        submissionTypes: ["영상", "콘텐츠"],
        teamModes: ["개인 선호", "팀 가능", "팀 선호"],
        minWeeklyHours: 3,
        goalKeywords: ["포트폴리오", "경험 쌓기", "상금"],
        requiredUnknowns: ["촬영 초상권/음원 사용권"],
        warnings: ["영상·음원 저작권 검수가 필요합니다."]
      }
    },
    {
      id: "opp-103",
      title: "ESG 사회문제 해결 대학생 기획 공모전",
      organization: "사회혁신재단",
      region: "전국",
      schoolScope: "대학생 팀",
      category: "공모전",
      benefitType: "사회문제 해결 기획 공모전",
      amountText: "상금 총 500만원",
      amountMax: 5000000,
      prizeText: "상금, 전문가 멘토링, 파일럿 실행비 검토",
      deadline: "2026-06-03 18:00",
      dday: 27,
      sourceType: "민간재단 공모전",
      documents: ["팀 참가신청서", "문제정의서", "실행계획서"],
      source: "contest-esg-social",
      contestFields: ["사회문제/공익", "환경/에너지", "기획/마케팅"],
      submissionTypes: ["기획서", "발표자료"],
      teamMode: "팀 권장",
      difficulty: "중간~높음",
      portfolioValue: "높음",
      rules: {
        contestFields: ["사회문제/공익", "환경/에너지", "기획/마케팅"],
        skillKeywords: ["기획", "리서치", "발표", "PM", "디자인"],
        submissionTypes: ["기획서", "발표자료"],
        teamModes: ["팀 가능", "팀 선호", "팀원 찾는 중"],
        minWeeklyHours: 5,
        goalKeywords: ["포트폴리오", "수상 경력", "경험 쌓기"],
        requiredUnknowns: ["팀 구성 요건", "오프라인 발표 여부"],
        warnings: ["팀 필수 여부와 발표 일정을 반드시 확인해야 합니다."]
      }
    }
  ],
  extractionQueue: [
    {
      id: "ext-001",
      title: "아산시 4차산업 인재육성 장학생",
      organization: "아산시미래장학회",
      source: "지자체 게시판 PDF",
      confidence: 0.83,
      missing: "중복수혜 조건",
      status: "PENDING",
      draftOpportunity: {
        title: "아산시 4차산업 인재육성 장학생",
        organization: "아산시미래장학회",
        region: "충청남도 아산시",
        schoolScope: "충남 출신 대학생",
        category: "장학금",
        benefitType: "재능개발 장학금",
        amountText: "총 200만원",
        amountMax: 2000000,
        deadline: "2026-05-24 18:00",
        dday: 17,
        sourceType: "AI 추출 검수",
        documents: ["신청서", "재학증명서", "활동계획서", "주민등록초본"],
        source: "asan-foundation",
        rules: {
          regionKeywords: ["충남", "충청남도", "아산시", "천안시"],
          schoolAny: true,
          minGpa: 3,
          maxIncomeBracket: null,
          majorKeywords: ["컴퓨터", "소프트웨어", "AI", "데이터", "공학"],
          requiredUnknowns: ["중복수혜 조건"],
          warnings: ["연말 결과보고서 제출이 필요합니다."]
        }
      }
    },
    {
      id: "ext-002",
      title: "은평구민 장학생 일반전형",
      organization: "은평구민장학재단",
      source: "장학재단 HWP",
      confidence: 0.71,
      missing: "거주기간 기준일",
      status: "PENDING",
      draftOpportunity: {
        title: "은평구민 장학생 일반전형",
        organization: "은평구민장학재단",
        region: "서울 은평구",
        schoolScope: "은평구 거주 대학생",
        category: "생활비",
        benefitType: "생활비성 장학금",
        amountText: "최대 200만원",
        amountMax: 2000000,
        deadline: "2026-05-18 18:00",
        dday: 11,
        sourceType: "AI 추출 검수",
        documents: ["신청서", "재학증명서", "성적증명서", "주민등록초본"],
        source: "eunpyeong-hwp",
        rules: {
          regionKeywords: ["은평구"],
          schoolAny: true,
          minGpa: 3,
          maxIncomeBracket: null,
          majorKeywords: [],
          requiredUnknowns: ["공고일 기준 거주기간"],
          warnings: ["타 장학금 수령액이 있을 시 차액 지급일 수 있습니다."]
        }
      }
    },
    {
      id: "ext-003",
      title: "해외연수 국비유학생 꿈나래전형",
      organization: "교육부 국립국제교육원",
      source: "공공기관 PDF",
      confidence: 0.9,
      missing: "금액 통화 정규화",
      status: "PENDING",
      draftOpportunity: {
        title: "국비유학생 선발시험 꿈나래전형",
        organization: "교육부 국립국제교육원",
        region: "전국",
        schoolScope: "대학 졸업예정자/졸업자",
        category: "교육/연수",
        benefitType: "해외대학원 장학금",
        amountText: "연 최대 USD 50,000",
        amountMax: 68000000,
        deadline: "2026-05-27 18:00",
        dday: 20,
        sourceType: "AI 추출 검수",
        documents: ["지원서", "성적증명서", "학업계획서", "어학성적"],
        source: "niied-pdf",
        rules: {
          regionKeywords: ["전국"],
          schoolAny: true,
          minGpa: 3.5,
          maxIncomeBracket: null,
          majorKeywords: [],
          requiredUnknowns: ["졸업예정 여부", "어학성적"],
          warnings: ["해외 대학원 입학 절차와 별도 요건을 확인해야 합니다."]
        }
      }
    },
    {
      id: "ext-101",
      title: "대학생 디지털 금융 서비스 기획 공모전",
      organization: "금융공익재단",
      source: "공식 공모전 수동 등록",
      confidence: 0.78,
      missing: "심사기준/저작권 조건",
      status: "PENDING",
      draftOpportunity: {
        title: "대학생 디지털 금융 서비스 기획 공모전",
        organization: "금융공익재단",
        region: "전국",
        schoolScope: "대학생 개인/팀",
        category: "공모전",
        benefitType: "서비스 기획 공모전",
        amountText: "상금 총 600만원",
        amountMax: 6000000,
        prizeText: "상금, 현직자 피드백, 우수팀 인터뷰",
        deadline: "2026-06-10 18:00",
        dday: 33,
        sourceType: "AI 추출 검수",
        documents: ["참가신청서", "서비스 기획서", "발표자료"],
        source: "contest-finance-service",
        contestFields: ["금융/경제", "기획/마케팅", "IT/소프트웨어"],
        submissionTypes: ["기획서", "발표자료"],
        teamMode: "개인/팀 모두 가능",
        difficulty: "중간",
        portfolioValue: "높음",
        rules: {
          regionKeywords: ["전국"],
          schoolAny: true,
          minGpa: null,
          maxIncomeBracket: null,
          majorKeywords: [],
          contestFields: ["금융/경제", "기획/마케팅", "IT/소프트웨어"],
          skillKeywords: ["기획", "리서치", "발표", "PM"],
          submissionTypes: ["기획서", "발표자료"],
          teamModes: ["개인 선호", "팀 가능", "팀 선호", "팀원 찾는 중"],
          minWeeklyHours: 3,
          goalKeywords: ["포트폴리오", "수상 경력", "경험 쌓기"],
          requiredUnknowns: ["심사기준", "저작권 귀속 조건"],
          warnings: ["아이디어 공개 범위와 금융 데이터 사용 조건을 확인해야 합니다."]
        }
      }
    }
  ],
  auditLogs: []
};
